Move tag editor JS into separate fil
iftechfoundation/ifdb pull request #1085
Opened 2024-11-09 10:15 UTC by salty-horse

I named the file `viewgame.js`, as I think most JS in `viewgame` should move there eventually.

2024-11-10 00:03 UTC, dfabulich requested changes

2024-11-10 00:03 UTC, dfabulich commented on www/viewgame.js
> +            var u = encodeURI8859(lst[i].tag);
Replace `encodeURI8859` (one more spot we won't have to fix later)

2024-11-10 00:03 UTC, dfabulich commented on www/viewgame.js
> +            var n = lst[i].isNew;
All these single-letter variable names make this code hard to read (I'll merge it anyway, though)

2024-11-10 19:59 UTC, salty-horse commented on www/viewgame.js
> +                    + `<span>${t}</span></label>&nbsp;<span class=details id="tagCnt${i}">`;
Doesn't it add whitepsace between elements that is sometimes significant in HTML?

2024-11-10 20:02 UTC, salty-horse commented on www/viewgame.js
> +}
I keep looking for a equivalent of Python's `sort(key=lambda t: t.tag.lower())` but this an improvement :)

2024-11-10 20:32 UTC, salty-horse commented on www/viewgame.js
> +class TagTable {
I'm new to modules. How do I pass in the `gameid` and `tagList` into it from the HTML file?

2024-11-10 20:38 UTC, salty-horse commented on www/viewgame.js
> +                    + t.replace(/"/g, "&#34;")
I don't think this is needed, as `t` is already `encodeHTML()`d

2024-11-11 03:31 UTC, dfabulich commented on www/viewgame.js
> +class TagTable {
Here's one way:
```
<script type=module src=viewgame.js></script>
<script type=module nonce='<?= $nonce ?>'>
import {whatever} from './viewgame.js'
whatever(<?= $gameid ?>)
</script>
```

2024-11-11 19:19 UTC, salty-horse commented on www/viewgame.js
> +            {"id": this.gameid, "tags": tags}, true);
That would require changes to jsonSend, no? Maybe best to do separately.

2024-11-15 06:43 UTC, dfabulich requested changes

2024-11-15 06:43 UTC, dfabulich commented on www/viewgame.js
> +    for (const [i, t] in Object.entries(memTagList))
Deleting tags isn't working for me. I think this `in` should be `of`

2024-11-15 06:45 UTC, dfabulich commented on www/viewgame.js
> +    for (const [i, t] in Object.entries(memTagList))
Also, in this branch, the "Delete Tags" dialog is missing its "Cancel" button.

2024-11-15 08:16 UTC, salty-horse commented
Added fixes in the latest commit, and fixed indentation in html.

2024-11-15 16:13 UTC, merged

2024-11-15 19:04 UTC, salty-horse commented
Whoops, looks like this generates `<script1 ` in the html. Will fix.

2024-11-15 19:07 UTC, salty-horse commented
Fixed in 625a77344030a6b050f857cb3c33a9c2a5f301ff