Use review creation date for display and sorting
iftechfoundation/ifdb pull request #1169
Opened 2024-11-22 09:44 UTC by salty-horse

Fixes #565, and addresses #1117.

For reviews where the edit date is a different day than the creation date, there's an "(edited: Mon, DD, YYYY)" addition. It's long, so if you have better ideas on how to display it, please share.

The personal page didn't display the date, so I removed it from the query.

Not shown, but I also checked that the RSS of game reviews is correct.

Game page:
![game_page](https://github.com/user-attachments/assets/6d285c89-b254-4d6f-bdd5-11caf0ee10ab)

Game page `&ratings` view:
![gamepage_ratings_view](https://github.com/user-attachments/assets/f0de429e-501e-4505-b27b-2a51d9f2839b)

User page:
![showuser](https://github.com/user-attachments/assets/4e414527-c8a5-4d9b-814a-9ad6dae87cff)

2024-11-23 06:48 UTC, dfabulich commented
There as many as _three_ dates for each review: its creation date, its embargo date, and the edit date (if any). #947 

In `newitems.php` we order by `greatest(reviews.createdate, ifnull(reviews.embargodate, '0000-00-00')) as d` which feels like the right thing to do.

> For reviews where the edit date is a different day than the creation date, there's an "(edited: Mon, DD, YYYY)" addition. It's long, so if you have better ideas on how to display it, please share.

I like the suggestion in #565 to add a note in a smaller font to the bottom of the review, giving us room to make the note as long/complicated as needed, and to display the computed sorting date at the top of the review.

> _This review was originally created on XXX, and was embargoed until YYY. It was last edited on ZZZ._

> _This review was originally created on XXX, and was last edited on YYY._

2024-11-23 06:50 UTC, dfabulich requested changes
There as many as _three_ dates for each review: its creation date, its embargo date, and the edit date (if any). #947 

In `newitems.php` we order by `greatest(reviews.createdate, ifnull(reviews.embargodate, '0000-00-00')) as d` which feels like the right thing to do.

> For reviews where the edit date is a different day than the creation date, there's an "(edited: Mon, DD, YYYY)" addition. It's long, so if you have better ideas on how to display it, please share.

I like the suggestion in #565 to add a note in a smaller font to the bottom of the review, giving us room to make the note as long/complicated as needed, and to display the computed sorting date at the top of the review.

> _This review was originally created on XXX, and was embargoed until YYY. It was last edited on ZZZ._

> _This review was originally created on XXX, and was last edited on YYY._

2024-11-23 07:16 UTC, salty-horse commented
Your suggestion includes creation date twice, at the top and bottom. Isn't that redundant?

I still think there should be an indication something was edited. Maybe an asterisk next to the top date?

Should the embargo date be public knowledge?

2024-11-23 21:51 UTC, dfabulich commented
> I still think there should be an indication something was edited. Maybe an asterisk next to the top date?

Sure, an asterisk would be fine.

> Should the embargo date be public knowledge?

I don't see why not. It's certainly publicly available in the IF Archive export.

> Your suggestion includes creation date twice, at the top and bottom. Isn't that redundant?

Kinda? I think the explanation would be confusing unless it juxtaposes the dates, which inherently requires repeating whichever date happens to be at the top.

For example, suppose we have three reviews:

1. Created Jan 1, embargoed until Jan 2, edited Jan 3
    * At the top: "Jan 2*"
    * At the bottom: "* This review was originally created on Jan 1, and it was embargoed until Jan 2. It was last edited on Jan 3."
2. Created Feb 1, embargoed until Feb 2
    * At the top: "Feb 2*"
    * At the bottom: "* This review was originally created on Feb 1, and it was embargoed until Feb 2."
3. Created Mar 1, edited Mar 3
    * At the top: "Mar 1*"
    * At the bottom: "* This review was originally created on Mar 1. It was last edited until Mar 3."

2024-11-29 04:51 UTC, dfabulich commented
OK, I think the consensus from the [forum thread](https://intfiction.org/t/72503) is to handle it like this:

* The main date at the top should be the "publication date," which is the greater of either the creation date or the embargo date
* If the review was edited, show the date with an asterisk, and then, at the end, show "* This review was last edited on [DATE]." (We don't need to repeat the publication date, or separately specify the creation date or the embargo date.)

2024-11-30 09:37 UTC, salty-horse commented
What about "rating only" reviews, that are just a rating, username, and date? (Shown in a screenshot in the first post)

2024-11-30 10:43 UTC, salty-horse commented
Pushed a new commit.

For big reviews, I used a footnote (with `<small>` element rather than `<div class="details">`), and added a title to the asterisk with the same text.

For ratings-only reviews, I left it on the same line as the creation date.
![edited](https://github.com/user-attachments/assets/234b54de-40c3-4ccf-ba4b-0f12fa6217b1)

2024-12-01 23:00 UTC, merged