Another option for the play online mini links
iftechfoundation/ifdb pull request #1231
Opened 2024-12-19 01:45 UTC by alice-blue

Similar to what I suggested, but this version doesn't require editing any existing messages, I don't think. It adds a separate sentence saying "You can also play online."

2024-12-19 03:30 UTC, dfabulich requested changes
Suggested replacement. This works for tricky cases I tried.

2024-12-19 03:30 UTC, dfabulich commented on www/viewgame
> +        }
```suggestion
        $playOnlineMiniLink = "";
        if ($playOnlineURL) {
            if ($onlineInterpreterType === "HTML" && !$compPri) {
                // Don't show "Play Online" mini link for HTML links; that's what the link itself does
                // ... unless the HTML is zipped, in which case we *do* need a Play Online link
            } else if ($zipnote || !$typedesc || $onlineInterpreterType === "HTML") {
                $playOnlineMiniLink = " <a href='$playOnlineURL'>Play Online</a>";
            } else {
                $playOnlineMiniLink = " You can also <a href='$playOnlineURL'>play online</a>.";
            }
        }
```

2024-12-19 03:43 UTC, dfabulich commented
https://github.com/iftechfoundation/ifdb/pull/1226#issuecomment-2552702002

> I honestly kinda prefer my version here in https://github.com/iftechfoundation/ifdb/pull/1226 better. @salty-horse do you have a preference?

2024-12-19 10:59 UTC, salty-horse commented
@dfabulich I prefer the button-next-to-title in the #1226 screenshot, and as a second choice the link-just-below-title.

2024-12-21 07:30 UTC, dfabulich commented
Let's go with #1233 instead

2024-12-21 07:30 UTC, closed without merging