Sort lists, polls, and clubs by newest by default
iftechfoundation/ifdb pull request #137
Opened 2021-04-04 09:38 UTC by dfabulich

2021-04-04 12:13 UTC, lkcampbell requested changes

2021-04-04 12:13 UTC, lkcampbell commented on www/searchutil.php
> +            'new' => array('moddate desc,', 'Newest First'),
In your other changes, Oldest First follows Newest First, but not in this change.

2021-04-04 12:13 UTC, lkcampbell commented on www/searchutil.php
> +            'new' => array('moddate desc,', 'Newest First'),
I noticed the Competitions browse list uses "Most Recent First". Suggest changing it to "Newest First" to be consistent.

2021-04-04 12:15 UTC, lkcampbell commented
@dfabulich, when I am doing reviews for you and the suggested changes are simple like these, do you prefer that I make the changes as part of the review, or just make the suggestions and leave the changes for you to make?

2021-04-05 19:34 UTC, dfabulich commented
Github has a nifty feature where you can "suggest changes" and edit the code in a comment; if I agree, I can then click a button to apply your suggestions. For small changes like renaming "Most Recent First" that's the ideal thing.

I'll just make the changes myself this time.

2021-04-05 19:37 UTC, merged