Reset review vote option
iftechfoundation/ifdb pull request #66
Opened 2021-03-11 01:37 UTC by Durafen

Closes [No way to remove a review vote #195](No way to remove a review vote #195)

2021-03-11 02:11 UTC, dfabulich requested changes
Nice work! A few suggestions

2021-03-11 02:11 UTC, dfabulich commented on www/reviews.php
> +                 where reviewid = '$qreviewid' and userid = '$curuser'");
```suggestion
```

2021-03-11 02:11 UTC, dfabulich commented on www/reviewvote
> +                 "Thanks for voting! Your vote has been reseted.", false);
```suggestion
    sendResponse("Vote Removed - Thanks!", false,
                 "Thanks for voting! Your vote has been removed.", false);
```

"Reseted" isn't an English word (though it totally ought to be)

2021-03-11 02:11 UTC, dfabulich commented on www/reviews.php
> +            . "return false;\">Reset</a> &nbsp; ";
```suggestion
            . "return false;\">Remove vote</a> &nbsp; ";
```

Seems like on https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/195 folks liked "Remove vote"

2021-03-11 02:23 UTC, dfabulich commented on www/reviews.php
> +            . "return false;\">Remove vote</a> &nbsp; ";
I just noticed that it _always_ includes the "Remove vote" link, even if you've never voted, and even right after you've removed your vote. (But fixing that sounds like a hassle.)

WDYT? Do you want to take a crack at making the link only show up when it's needed? Or I can just merge this now and we can file that as a separate bug?

2021-03-11 14:42 UTC, Durafen commented
Updated it, so it dynamically updates the "Remove vote" option.

2021-03-16 06:18 UTC, dfabulich commented
Thanks! (Sorry for the delay in reviewing.)

2021-03-16 06:18 UTC, merged