Fix for https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/12
iftechfoundation/ifdb pull request #89
Opened 2021-03-19 23:08 UTC by lkcampbell

Add Open Graph elements to view game page

2021-03-19 23:16 UTC, dfabulich commented
How did you set up that tunnel tool?

2021-03-19 23:22 UTC, lkcampbell commented
Used a Node.js tool called localtunnel. Here's the info:

https://samvikshana.weebly.com/blog/how-to-use-facebook-sharing-debugger-and-twitter-card-validator-with-localhost-urls

2021-03-20 03:27 UTC, dfabulich requested changes

2021-03-20 03:27 UTC, dfabulich commented on www/viewgame
> +    $extraHead .= "&amp;thumbnail=175x175\"/>";
```suggestion
    $extraHead .= get_root_url() . "viewgame?coverart&amp;id=$id\"/>";
```

I don't think we want to use a small thumbnail for this; we should use the biggest size we have. Stuff I've read online indicates that really big images (1200x1200) are good. https://iamturns.com/open-graph-image-size/

2021-03-20 19:09 UTC, merged

2021-03-20 22:16 UTC, curiousdannii commented
Maybe the title could be "TITLE by AUTHOR"?

2021-03-20 22:41 UTC, lkcampbell commented
@curiousdannii that would certainly be easy enough to add.

I will post the idea at intfiction.org and see what people think.